const CartActionTypes = {
  SET_CART: "SET_CART",
  ADD_TO_CART: "ADD_TO_CART",
  CHANGE_QUANTITY: "CHANGE_QUANTITY",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  EMPTY_CART: "EMPTY_CART"
};

export default CartActionTypes;
